name: Spell Checker
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:
jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
      - name: Check Spelling
        id: spellcheck
        uses: rojopolis/spellcheck-github-actions@0.52.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown
