matrix:
  - name: Markdown
    expect_match: false
    apsell:
      mode: en
    dictionary:
      wordlists:
        - .wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra:
      - pyspelling.filters.html:
          comments: false
          attributes:
            - alt
          ignores:
            - ":matches(code, pre)"
            - "code"
            - "pre"
            - "blockquote"
    sources:
      - "**/*.md"
    default_encoding: utf-8
